### PR TITLE
Updating models with C++11 features.

### PR DESCRIPTION
**Pull request by rolanddenis**
Updating models using new keyword `= delete` for deleted members (instead of using private non-implemented members) and `= default` for compiler-generated special members.

The class does not compile until the destructor is modified (`= default` or implemented).

### CODE REVIEW

**Comment by rolanddenis** [comment]
What version did I specify in Changelog ? 0.3 ?

**Comment by dcoeurjo** [comment]
Yep.. I didn't remember there was a change log for that ;)

**Comment by rolanddenis** [comment]
Done :octocat:

**Comment by dcoeurjo** [comment]
Thanks. Merging.

**Pull request merged**
